-- M1.7 — Dev Organ Proposal Queue
-- Run: psql -U ado_app -d ado -f 027_dev_organ_proposals.sql
--
-- Stores all improvement proposals generated by MiganCore's Dev Organ.
-- Creator (Fahmi) reviews proposals here before any code touches production.
--
-- Flow:
--   MiganCore observes → generates proposal → stored here (stage=proposed)
--   Fahmi reviews in Playground UI → sets creator_verdict (approved/rejected)
--   QA gates run in sandbox → gate_results updated
--   If all gates pass + approved → stage=deployable → manual deploy
--
-- Risk levels (from dev_organ.py): low | medium | high | critical
-- Stages: observed → diagnosed → proposed → patched → tested → iterated
--         → validated → deployable → deployed → monitored → rolled_back | blocked

CREATE TABLE IF NOT EXISTS dev_organ_proposals (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Authorship
    tenant_id        UUID REFERENCES tenants(id) ON DELETE CASCADE,
    created_by       TEXT NOT NULL DEFAULT 'core_brain',   -- agent_id or 'owner'

    -- Proposal content
    title            TEXT NOT NULL,
    problem          TEXT NOT NULL,
    hypothesis       TEXT NOT NULL DEFAULT '',
    touched_paths    TEXT[] NOT NULL DEFAULT '{}',
    tests            TEXT[] NOT NULL DEFAULT '{}',
    rollback_plan    TEXT NOT NULL DEFAULT '',
    metadata         JSONB NOT NULL DEFAULT '{}',

    -- Classification
    risk_level       TEXT NOT NULL DEFAULT 'medium'
                         CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    source           TEXT NOT NULL DEFAULT 'auto'           -- auto | owner_command | tool_failure | eval_failure
                         CHECK (source IN ('auto', 'owner_command', 'tool_failure', 'eval_failure', 'manual')),

    -- Lifecycle
    stage            TEXT NOT NULL DEFAULT 'proposed'
                         CHECK (stage IN (
                             'observed', 'diagnosed', 'proposed', 'patched',
                             'tested', 'iterated', 'validated', 'deployable',
                             'deployed', 'monitored', 'rolled_back', 'blocked'
                         )),

    -- QA gate results (array of {name, passed, detail})
    gate_results     JSONB NOT NULL DEFAULT '[]',
    gate_run_at      TIMESTAMPTZ,

    -- Creator decision
    creator_verdict  TEXT CHECK (creator_verdict IN ('approved', 'rejected', NULL)),
    creator_notes    TEXT,
    decided_at       TIMESTAMPTZ,

    -- Timestamps
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Fast queries for Playground UI
CREATE INDEX IF NOT EXISTS idx_proposals_stage      ON dev_organ_proposals(stage);
CREATE INDEX IF NOT EXISTS idx_proposals_verdict    ON dev_organ_proposals(creator_verdict) WHERE creator_verdict IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_proposals_risk       ON dev_organ_proposals(risk_level);
CREATE INDEX IF NOT EXISTS idx_proposals_created    ON dev_organ_proposals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_proposals_tenant     ON dev_organ_proposals(tenant_id) WHERE tenant_id IS NOT NULL;

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION _set_proposals_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_proposals_updated_at ON dev_organ_proposals;
CREATE TRIGGER trg_proposals_updated_at
    BEFORE UPDATE ON dev_organ_proposals
    FOR EACH ROW EXECUTE FUNCTION _set_proposals_updated_at();
