#!/bin/bash
# ============================================================
# ADO Standalone Deploy Wizard — Day 67
# ============================================================
# This script is for client IT staff to manually deploy an
# ADO instance on a fresh Ubuntu 22.04 VPS.
#
# Prerequisites:
#   - Ubuntu 22.04 LTS (fresh install)
#   - Minimum 8GB RAM, 4 vCPU, 80GB disk
#   - docker-compose.yml already in /opt/ado-client/
#     (generated by Migancore Clone Manager and provided by
#      your Migancore account manager)
#
# Usage:
#   1. Upload docker-compose.yml to /opt/ado-client/
#   2. Run: bash setup_new_ado.sh
#   3. Follow the prompts
#
# Generated by: Migancore Clone Manager
# Powered by: Migancore × PT Tiranyx Digitalis Nusantara
# ============================================================

set -euo pipefail

# ─── Config ───────────────────────────────────────────────────────────────────
DEPLOY_DIR="${DEPLOY_DIR:-/opt/ado-client}"
ADO_PORT="${ADO_PORT:-18000}"
SWAP_SIZE="${SWAP_SIZE:-4G}"
LOG_FILE="/tmp/ado_deploy_$(date +%Y%m%d_%H%M%S).log"

# ─── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $*" | tee -a "$LOG_FILE"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*" | tee -a "$LOG_FILE"; }
err()     { echo -e "${RED}[ERROR]${NC} $*" | tee -a "$LOG_FILE"; }
section() { echo -e "\n${GREEN}==============================${NC}" | tee -a "$LOG_FILE"
            echo -e "${GREEN} $*${NC}" | tee -a "$LOG_FILE"
            echo -e "${GREEN}==============================${NC}" | tee -a "$LOG_FILE"; }

# ─── Preflight ────────────────────────────────────────────────────────────────
section "ADO DEPLOY WIZARD — Preflight"

# Must be root
if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root. Try: sudo bash $0"
    exit 1
fi

# Check OS
if ! grep -q "Ubuntu 22.04\|Ubuntu 24.04" /etc/os-release 2>/dev/null; then
    warn "Tested on Ubuntu 22.04/24.04. Other distros may work but are unsupported."
fi

# Check RAM
RAM_GB=$(free -g | awk '/^Mem:/{print $2}')
if [[ $RAM_GB -lt 7 ]]; then
    err "Minimum 8GB RAM required. Detected: ${RAM_GB}GB."
    err "ADO + Qwen 7B GGUF requires ~5.5GB VRAM/RAM minimum."
    exit 1
fi
info "RAM: ${RAM_GB}GB ✓"

# Check disk
DISK_GB=$(df -BG / | tail -1 | awk '{print $4}' | tr -d G)
if [[ $DISK_GB -lt 40 ]]; then
    err "Minimum 40GB free disk required. Available: ${DISK_GB}GB"
    exit 1
fi
info "Disk free: ${DISK_GB}GB ✓"

# Check compose file
if [[ ! -f "$DEPLOY_DIR/docker-compose.yml" ]]; then
    err "docker-compose.yml not found at $DEPLOY_DIR/"
    err "Please upload it first, then re-run this script."
    err "Contact your Migancore account manager if you don't have it."
    exit 1
fi
info "docker-compose.yml found ✓"

echo ""
info "Preflight PASS — starting installation"
info "Log: $LOG_FILE"

# ─── Step 1: OS Update ────────────────────────────────────────────────────────
section "Step 1/7 — OS Update"
apt-get update -qq 2>&1 | tee -a "$LOG_FILE"
apt-get upgrade -y -qq 2>&1 | tee -a "$LOG_FILE"
info "OS updated ✓"

# ─── Step 2: Docker ───────────────────────────────────────────────────────────
section "Step 2/7 — Docker"
if command -v docker &>/dev/null; then
    info "Docker already installed: $(docker --version)"
else
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh 2>&1 | tee -a "$LOG_FILE"
    systemctl enable docker && systemctl start docker
    info "Docker installed ✓"
fi

# ─── Step 3: Docker Compose Plugin ───────────────────────────────────────────
section "Step 3/7 — Docker Compose"
if docker compose version &>/dev/null; then
    info "Docker Compose already available: $(docker compose version)"
else
    info "Installing Docker Compose plugin..."
    apt-get install -y docker-compose-plugin 2>&1 | tee -a "$LOG_FILE"
    info "Docker Compose installed ✓"
fi

# ─── Step 4: Nginx + Certbot ──────────────────────────────────────────────────
section "Step 4/7 — Nginx + Certbot"
if ! command -v nginx &>/dev/null; then
    apt-get install -y nginx certbot python3-certbot-nginx 2>&1 | tee -a "$LOG_FILE"
    systemctl enable nginx
    info "Nginx + Certbot installed ✓"
else
    info "Nginx already installed ✓"
fi

# ─── Step 5: Swap ────────────────────────────────────────────────────────────
section "Step 5/7 — Swap"
if swapon --show | grep -q swapfile 2>/dev/null; then
    info "Swap already configured ✓"
else
    info "Setting up $SWAP_SIZE swap..."
    fallocate -l "$SWAP_SIZE" /swapfile
    chmod 600 /swapfile
    mkswap /swapfile 2>&1 | tee -a "$LOG_FILE"
    swapon /swapfile
    echo "/swapfile none swap sw 0 0" >> /etc/fstab
    # Reduce swappiness — only use swap when RAM > 90% full
    sysctl vm.swappiness=10
    echo "vm.swappiness=10" >> /etc/sysctl.conf
    info "Swap $SWAP_SIZE configured, swappiness=10 ✓"
fi

# ─── Step 6: Deploy ADO ───────────────────────────────────────────────────────
section "Step 6/7 — Deploy ADO"
mkdir -p "$DEPLOY_DIR"
cd "$DEPLOY_DIR"

info "Starting containers..."
docker compose up -d 2>&1 | tee -a "$LOG_FILE"

info "Waiting 45s for containers to initialize..."
sleep 45

# ─── Step 7: Health Check ─────────────────────────────────────────────────────
section "Step 7/7 — Health Check"
HEALTH_URL="http://127.0.0.1:${ADO_PORT}/health"
MAX_RETRIES=10
RETRY=0

while [[ $RETRY -lt $MAX_RETRIES ]]; do
    STATUS=$(curl -sf "$HEALTH_URL" 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('status','?'))" 2>/dev/null || echo "")
    if [[ "$STATUS" == "ok" || "$STATUS" == "healthy" ]]; then
        info "Health check PASS: $STATUS ✓"
        break
    fi
    RETRY=$((RETRY+1))
    warn "Attempt $RETRY/$MAX_RETRIES — ADO not ready yet (status='$STATUS'), retrying in 10s..."
    sleep 10
done

if [[ $RETRY -eq $MAX_RETRIES ]]; then
    warn "Health check timed out — check containers manually:"
    warn "  cd $DEPLOY_DIR && docker compose logs api"
fi

# ─── Done ────────────────────────────────────────────────────────────────────
section "DEPLOY COMPLETE"
echo ""
docker compose ps 2>&1 | tee -a "$LOG_FILE"
echo ""
info "ADO API running at: http://127.0.0.1:${ADO_PORT}"
info ""
info "Next steps:"
info "  1. Pull LLM model (takes 5-10 min):"
info "     docker exec ado-ollama-1 ollama pull qwen2.5:7b-instruct-q4_K_M"
info ""
info "  2. Setup nginx reverse proxy (replace YOUR_DOMAIN):"
info "     certbot --nginx -d YOUR_DOMAIN"
info ""
info "  3. Create admin account:"
info "     curl -X POST http://127.0.0.1:${ADO_PORT}/v1/auth/register \\"
info "       -H 'Content-Type: application/json' \\"
info "       -d '{\"email\":\"admin@yourcompany.com\",\"password\":\"ChangeMe!\"}'"
info ""
info "Full log: $LOG_FILE"
info "Support: support@migancore.com"
