"""
DevOrganProposal ORM model — M1.7 improvement proposal queue.

Each row is an improvement idea generated by MiganCore's Dev Organ
(or by Fahmi directly). Fahmi reviews proposals in the Playground UI
and approves/rejects before any code enters production.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import DateTime, String, Text, ARRAY, JSON, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from models.base import Base


class DevOrganProposal(Base):
    __tablename__ = "dev_organ_proposals"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # Authorship
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True), nullable=True
    )
    created_by: Mapped[str] = mapped_column(
        String(128), nullable=False, default="core_brain"
    )

    # Proposal content
    title: Mapped[str] = mapped_column(Text, nullable=False)
    problem: Mapped[str] = mapped_column(Text, nullable=False)
    hypothesis: Mapped[str] = mapped_column(Text, nullable=False, default="")
    touched_paths: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    tests: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    rollback_plan: Mapped[str] = mapped_column(Text, nullable=False, default="")
    metadata_: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSON, nullable=False, default=dict
    )

    # Classification
    risk_level: Mapped[str] = mapped_column(
        String(16), nullable=False, default="medium"
    )
    source: Mapped[str] = mapped_column(
        String(32), nullable=False, default="auto"
    )

    # Lifecycle
    stage: Mapped[str] = mapped_column(
        String(32), nullable=False, default="proposed"
    )

    # QA gate results
    gate_results: Mapped[list[dict[str, Any]]] = mapped_column(
        JSON, nullable=False, default=list
    )
    gate_run_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Creator decision
    creator_verdict: Mapped[str | None] = mapped_column(
        String(16), nullable=True
    )
    creator_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    decided_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": str(self.id),
            "created_by": self.created_by,
            "title": self.title,
            "problem": self.problem,
            "hypothesis": self.hypothesis,
            "touched_paths": self.touched_paths or [],
            "tests": self.tests or [],
            "rollback_plan": self.rollback_plan,
            "risk_level": self.risk_level,
            "source": self.source,
            "stage": self.stage,
            "gate_results": self.gate_results or [],
            "gate_run_at": self.gate_run_at.isoformat() if self.gate_run_at else None,
            "creator_verdict": self.creator_verdict,
            "creator_notes": self.creator_notes,
            "decided_at": self.decided_at.isoformat() if self.decided_at else None,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "metadata": self.metadata_ or {},
        }
